### ISSUE TITLE
Is it possible to make the Colab create a 3D model from a single image of a whale? 

### ISSUE THREAD

**Issue by hmatt843** [facebookresearch/phosa#16]
Hi,
I went through a Colab example (PHOSA Colab https://colab.research.google.com/drive/1QIoL2g0jdt5E-vYKCIojkIz21j3jyEvo?usp=sharing ) without having issues. But when I tried to change it to a whale jpg (https://bdmlr.org.uk/wp-content/uploads/2020/01/animal-humpback_whale.png) it failed out on several code blocks.
Is what I'm trying to do (get a 3D model of a single whale image) possible with this?

**Comment by jasonyzhang** [comment]
Hi,

The default code is only intended to work for images with humans and bicycles. It should be possible to add any category that detectron2 can detect and segment. Unfortunately, detectron2 cannot segment whales out of the box since whales are not a COCO object category.

If you are looking to do 3D object reconstruction from images, I would recommend looking at approaches for deformable objects. Some examples of recent works include [A-CSM](https://github.com/nileshkulkarni/acsm) and [U-CMR](https://github.com/shubham-goel/ucmr). However, I don't think these approaches work on whales specifically.

Best,
Jason
