### ISSUE TITLE
providing script or screenshot or video tutorial for the mesh pre-processing step

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#19]
Hi Jason,

Could you please provide the scripts or some screenshots how you perform the following steps?

For the pre-processing, 

1.  we first fill in the holes of the raw mesh models (e.g. the holes in the wheels or tennis racket) to make the projection of the 3D
models consistent with the silhouettes obtained by the instance segmentation algorithm [35]. 

2. Then, we perform a TSDF fusion approach [59] that converts the raw meshes to be watertight and simplified. 

3. Finally, we reduce the number of mesh vertices using MeshLab [3].

Thanks a lot

**Comment by jhugestar** [comment]
Hi @monacv,

Unfortunately, we do not have a script, since the process is not fully automatic. (sorry that we cannot share the mesh directly due to the license issue). Let me try to give you a bit more descriptions. 

Step 1: Hole filling
- Note that this step is only necessary if the raw mesh has holes. (For example, it is not necessary for baseball bat)
- We use [Blender](https://www.blender.org/) to edit the mesh. Our mesh editing is actually quite naive; we just placed 3D boxes, discs, or arbitrary shapes to fill in the holes. After finishing the editing save the mesh into off file. 

Step 2: Producing watertight mesh
- We use mesh-fusion which takes "off" files as input: https://github.com/davidstutz/mesh-fusion
- You can just follow their scripts. Specifically, put your "off" file into "examples/0_in" folder and run the following commands
```
python 1_scale.py --in_dir=examples/0_in/ --out_dir=examples/1_scaled/
python 2_fusion.py --mode=render --in_dir=examples/1_scaled/ --depth_dir=examples/2_depth/ --out_dir=examples/2_watertight/
python 2_fusion.py --mode=fuse --in_dir=examples/1_scaled/ --depth_dir=examples/2_depth/ --out_dir=examples/2_watertight/
```
- You can find the output "off" file in "2_watertight" folder. 



Step 3: Reducing number of vertices
- Load the output of step 2 (off file) in meshlap
- In meshlab, find the following in the menu:
Filters-> Remeshing, Simplification and Reconstruction -> Simplification: Quadric Edge Collapse Decimation
- Change the number of faces:
    “Target number of faces: 1000”
- Click the "apply" button
- Save the output



@jasonyzhang
