### ISSUE TITLE
How do I find the MEAN_INTRINSIC_SCALE, INTERACTION_THRESHOLD, DEFAULT_LOSS_WEIGHTS, BBOX_EXPANSION_PARTS, and BBOX_EXPANSION for a new object?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#33]
Thanks a lot for your replies to my previous issues. They were really helpful. 

Imagine I have a new class, a wine bottle (which is in COCO). How can I find the following information about it? So far, I gave the same of tennis to it and I ended up with something like the following:

![bottle9](https://user-images.githubusercontent.com/76495162/114253954-bcf27c00-997a-11eb-85f1-5b7a12860dca.jpg)

![bottle9](https://user-images.githubusercontent.com/76495162/114253950-b6640480-997a-11eb-9c06-1fea20c0f177.jpg)

all in phosa/constant.py file:
```
MEAN_INTRINSIC_SCALE
INTERACTION_THRESHOLD
DEFAULT_LOSS_WEIGHTS
BBOX_EXPANSION_PARTS
BBOX_EXPANSION
``` 

Also, in the original image, there is no interaction between the mouth and the bottle however, the reconstruction is forcing the interaction between the mouth and bottle. Do you know what's the reason for this? Is there a way I could perhaps fix this? 

Thanks a lot for your time.

**Comment by jasonyzhang** [comment]
They are hyperparameters that are tuned per category. You can initialize them with the hyperparameters for the most similar object already in the constants file.

If there is no explicit interaction defined between bottle and mouth, two possible reasons for the closeness come to mind. It is possible that the coarse  interaction loss (`lw_inter`) is too high. More likely, it is due to the human pose estimation. We use the EFT regressor from FrankMocap, which is trained with orthographic projection (like all human pose estimation approaches that I am aware of). For PHOSA, we switch the camera model to perspective projection. For images like this one where the camera is closeup, this camera conversion can produce perspective artifacts, causing the mesh to be misaligned with the image. One possibility is to increase the focal length significantly so that the human pose estimation is more accurate.

Best,
Jason
