### ISSUE TITLE
instance_segmentation failed

### ISSUE THREAD

**Issue by MohsenAziz** [facebookresearch/phosa#44]
i'm using the new detectron model , and the mask that follow the segmentation step is not accurate enough , can you help?

![1](https://user-images.githubusercontent.com/58271302/146585359-d63e2e3a-fd36-4c63-9a1e-9357abab5c61.jpg)
![2](https://user-images.githubusercontent.com/58271302/146585365-c983a8f5-7f0e-43eb-b93a-9f2b9bdcc30f.jpg)
![3](https://user-images.githubusercontent.com/58271302/146585374-9058c18a-0d7e-4e6e-8da7-af21df4737eb.jpg)

**Comment by jasonyzhang** [comment]
Hi,

The poor segmentation is likely due to minor changes in the PointRend model that are not reflected in the v0.2.1 detectron2 commit used by this project.

I am now directly hosting the PointRend model weights, so the easiest solution is to use the old version of detectron with those weights (since those weights and model definitions will never change).

If you wish to use the latest and greatest detectron2 segmentation model, you will need to update the version of detectron2 in the external folder. Note that the latest detectron models may require a newer version of pytorch, so you will need to re-build NMR from source.

Best,
Jason
